name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        lua: [5.3]
        luarocks: [3.3.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: tests with lua-${{ matrix.lua }}
    steps:
    - uses: actions/checkout@v1
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{ matrix.lua }}
    - uses: leafo/gh-actions-luarocks@v2
      with:
        luarocksVersion: ${{ matrix.luarocks }}
    - run: cd $GITHUB_WORKSPACE/template && luarocks install busted
    #- run: cd $GITHUB_WORKSPACE/template && luarocks make
    - run: lua $GITHUB_WORKSPACE/template/main.lua
